[phases.setup]
nixPkgs = ['python311', 'gunicorn']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = [
  'python3 manage.py migrate',
  'python3 manage.py collectstatic --noinput',
  'python3 manage.py setup_media',
  'python3 manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username=\'admin\').exists() or User.objects.create_superuser(\'admin\', \'admin@example.com\', \'admin\')"'
]

[phases.start]
cmd = 'gunicorn config.wsgi:application --bind 0.0.0.0:$PORT'
