services:
  # Django Web Service
  - type: web
    name: django-travel-api
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
      python manage.py setup_media
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: travel-partner-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11.0"

databases:
  # PostgreSQL Database
  - name: travel-partner-db
    plan: free
    databaseName: travel_partner_db
    user: travel_partner_user 