# Generated by Django 4.2.23 on 2025-07-16 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToursServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tours', models.PositiveIntegerField()),
                ('types_of_tours', models.JSONField(default=list, help_text='Array of tour types')),
                ('custom_tour_type', models.CharField(blank=True, max_length=255, null=True)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('group_size_min', models.PositiveIntegerField()),
                ('group_size_max', models.PositiveIntegerField()),
                ('preference', models.CharField(blank=True, max_length=255, null=True)),
                ('offers_custom_tours', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tours_services', to='partner.partner')),
            ],
        ),
        migrations.CreateModel(
            name='LocationCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_location', models.CharField(max_length=255)),
                ('destinations', models.JSONField(default=list, help_text='Array of destination IDs')),
                ('languages', models.JSONField(default=list, help_text='Array of languages')),
                ('regions', models.JSONField(default=list, help_text='Array of regions')),
                ('pan_india', models.BooleanField(default=False)),
                ('seasons', models.JSONField(default=list, help_text='Array of seasons')),
                ('timezone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_coverage', to='partner.partner')),
            ],
        ),
        migrations.CreateModel(
            name='LegalBanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_or_aadhaar', models.CharField(max_length=20)),
                ('business_proof_file', models.FileField(blank=True, null=True, upload_to='business_proofs/')),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('company_type', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_banking', to='partner.partner')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_of_provider', models.JSONField(default=list, help_text='Array of provider types')),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('years', models.PositiveIntegerField(help_text='Years in business')),
                ('website', models.URLField(blank=True, null=True)),
                ('reg_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registration Number')),
                ('address', models.TextField()),
                ('employees', models.PositiveIntegerField()),
                ('seasonal', models.BooleanField(default=False)),
                ('annual_bookings', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_details', to='partner.partner')),
            ],
        ),
    ]
