# Generated by Django 4.2.7 on 2025-07-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalbanking',
            name='pan_or_aadhaar',
        ),
        migrations.AddField(
            model_name='legalbanking',
            name='pan_or_aadhaar_file',
            field=models.FileField(blank=True, help_text='Upload PAN/Aadhaar document (PDF/Image, max 10MB)', null=True, upload_to='pan_aadhaar_docs/'),
        ),
        migrations.AddField(
            model_name='legalbanking',
            name='pan_or_aadhaar_text',
            field=models.CharField(blank=True, help_text='PAN/Aadhaar number as text', max_length=20, null=True),
        ),
    ]
