# Generated by Django 4.2.7 on 2025-07-21 06:04

import apps.partner.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_remove_legalbanking_pan_or_aadhaar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalbanking',
            name='pan_or_aadhaar_file',
            field=models.FileField(blank=True, help_text='Upload PAN/Aadhaar document (PDF/Image, max 10MB)', null=True, upload_to='pan_aadhaar_docs/', validators=[apps.partner.validators.validate_document_file]),
        ),
    ]
