# Generated by Django 4.2.7 on 2025-07-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_add_status_to_partner'),
        ('partner', '0003_alter_legalbanking_pan_or_aadhaar_file'),
    ]

    operations = [
    ]
