# Generated by Django 4.2.7 on 2025-07-24 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_remove_businessdetails_address_businessdetails_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='partner.partner')),
            ],
        ),
    ]
