# Generated by Django 4.2.7 on 2025-07-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_alter_businessdetails_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start_date',
        ),
        migrations.AddField(
            model_name='tour',
            name='contact_link',
            field=models.URLField(blank=True, null=True, verbose_name='Contact Link (Optional)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='destinations',
            field=models.JSONField(default=list, help_text='List of destinations', verbose_name='Destination(s)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Tour Duration (Days)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='duration_nights',
            field=models.PositiveIntegerField(default=1, verbose_name='Tour Duration (Nights)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='provider_name',
            field=models.CharField(default='Default title', max_length=255, verbose_name='Tour Provider Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='title',
            field=models.CharField(default='FIT', max_length=255, verbose_name='Tour Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_link',
            field=models.URLField(default='Default provider', verbose_name='Tour Link (External URL)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('FIT', 'FIT'), ('Group', 'Group'), ('Customizable', 'Customizable')], default='Example.com', max_length=20, verbose_name='Tour Type'),
            preserve_default=False,
        ),
    ]
