# Generated by Django 4.2.7 on 2025-07-30 05:17

import apps.partner.utils
import apps.partner.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_alter_locationcoverage_primary_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='categories',
            field=models.JSONField(default=list, help_text='List of categories like Honeymoon, Adventure, Family, Beach, etc.', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='tour',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_covers/', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='tour',
            name='departure_cities',
            field=models.JSONField(default=list, help_text='List of departure cities', verbose_name='Departure Cities'),
        ),
        migrations.AddField(
            model_name='tour',
            name='departure_months',
            field=models.JSONField(default=list, help_text='List of months (Jan-Dec)', verbose_name='Departure Months'),
        ),
        migrations.AddField(
            model_name='tour',
            name='discount_details',
            field=models.TextField(blank=True, null=True, verbose_name='Discount Details'),
        ),
        migrations.AddField(
            model_name='tour',
            name='highlights',
            field=models.JSONField(default=list, help_text='List of tour highlights', verbose_name='Tour Highlights'),
        ),
        migrations.AddField(
            model_name='tour',
            name='includes_flights',
            field=models.BooleanField(default=False, verbose_name='Includes Flights?'),
        ),
        migrations.AddField(
            model_name='tour',
            name='includes_hotels',
            field=models.BooleanField(default=False, verbose_name='Includes Hotels?'),
        ),
        migrations.AddField(
            model_name='tour',
            name='includes_meals',
            field=models.BooleanField(default=False, verbose_name='Includes Meals?'),
        ),
        migrations.AddField(
            model_name='tour',
            name='includes_transfers',
            field=models.BooleanField(default=False, verbose_name='Includes Transfers?'),
        ),
        migrations.AddField(
            model_name='tour',
            name='offers_type',
            field=models.JSONField(default=list, help_text='Early Bird Offer, Group Discount, Seasonal Discount', verbose_name='Offers Type'),
        ),
        migrations.AddField(
            model_name='tour',
            name='price_type',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Starting From', 'Starting From')], default='Starting From', max_length=20, verbose_name='Price Type'),
        ),
        migrations.AddField(
            model_name='tour',
            name='promotional_tagline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Promotional Tagline'),
        ),
        migrations.AddField(
            model_name='tour',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Starting Price (Per Person)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='summary',
            field=models.TextField(blank=True, help_text='1-3 lines describing the experience', null=True, verbose_name='Tour Summary'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tags',
            field=models.JSONField(default=list, help_text='SEO tags and keywords', verbose_name='Tags/Keywords'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_drop_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tour Drop Location'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_start_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tour Start Location'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_status',
            field=models.CharField(choices=[('Live', 'Live'), ('Draft', 'Draft'), ('Coming Soon', 'Coming Soon')], default='Draft', max_length=20, verbose_name='Tour Status'),
        ),
        migrations.AddField(
            model_name='tour',
            name='visa_support',
            field=models.BooleanField(default=False, verbose_name='Visa Support Provided?'),
        ),
        migrations.AddField(
            model_name='tour',
            name='visibility_score',
            field=models.PositiveIntegerField(default=0, verbose_name='Tripsetter Visibility Score'),
        ),
        migrations.AlterField(
            model_name='legalbanking',
            name='business_proof_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.partner.utils.get_secure_upload_path),
        ),
        migrations.AlterField(
            model_name='legalbanking',
            name='pan_or_aadhaar_file',
            field=models.FileField(blank=True, help_text='Upload PAN/Aadhaar document (PDF/Image, max 10MB)', null=True, upload_to=apps.partner.utils.get_secure_upload_path, validators=[apps.partner.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Tour Duration (Days)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration_nights',
            field=models.PositiveIntegerField(default=0, verbose_name='Tour Duration (Nights)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='provider_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tour Provider Name'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tour Title'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_link',
            field=models.URLField(blank=True, null=True, verbose_name='Tour Link (External URL)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('FIT', 'FIT'), ('Group', 'Group'), ('Customizable', 'Customizable')], default='FIT', max_length=20, verbose_name='Tour Type'),
        ),
    ]
